// <auto-generated />
using System;
using Lexify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lexify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704130839_AddUserEnglishLevel")]
    partial class AddUserEnglishLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lexify.Domain.Entities.AiCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("call_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_hash");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_ai_logs_errors")
                        .HasFilter("success = FALSE");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_ai_logs_user")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("CallType", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_ai_logs_type");

                    b.HasIndex("Provider", "Success")
                        .HasDatabaseName("idx_ai_logs_provider");

                    b.ToTable("ai_call_logs", null, t =>
                        {
                            t.HasCheckConstraint("chk_ai_logs_duration", "duration_ms >= 0");

                            t.HasCheckConstraint("chk_ai_logs_provider", "provider IN ('ollama', 'openai')");

                            t.HasCheckConstraint("chk_ai_logs_type", "call_type IN ('format_words', 'generate_test', 'suggest_title')");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<string>("GivenAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("given_answer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int?>("TimeSpentMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_ms");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("idx_attempt_answers_wrong")
                        .HasFilter("is_correct = FALSE");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_attempt_answers_question");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("uq_attempt_question");

                    b.ToTable("attempt_answers", null, t =>
                        {
                            t.HasCheckConstraint("chk_answers_time", "time_spent_ms IS NULL OR time_spent_ms >= 0");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("idx_audit_admin");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_created");

                    b.HasIndex("Action", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_action");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("idx_audit_target");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Lexify.Domain.Entities.BlockTag", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("BlockId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("idx_block_tags_tag");

                    b.ToTable("block_tags", (string)null);
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Language", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("native_name");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_languages_code");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("idx_languages_active");

                    b.ToTable("languages", null, t =>
                        {
                            t.HasCheckConstraint("chk_languages_code", "code ~ '^[a-z]{2,5}$'");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid?>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("idx_questions_hash");

                    b.HasIndex("TestId")
                        .HasDatabaseName("idx_questions_test_id");

                    b.HasIndex("WordId")
                        .HasDatabaseName("idx_questions_word_id")
                        .HasFilter("word_id IS NOT NULL");

                    b.HasIndex("TestId", "SortOrder")
                        .HasDatabaseName("idx_questions_sort");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("chk_questions_type", "question_type IN ('translate_to_native', 'translate_to_foreign', 'fill_in_sentence', 'multi_select_theme', 'open_answer')");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_question_options_correct")
                        .HasFilter("is_correct = TRUE");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("Lexify.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedBy");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Lexify.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("value_type");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("system_settings", null, t =>
                        {
                            t.HasCheckConstraint("chk_settings_type", "value_type IN ('string', 'bool', 'int', 'json')");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tags_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tags_user_name");

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("chk_tags_name", "name ~ '^[a-z0-9\\u0430-\\u044f\\u0451\\u0456\\u0457\\u0454_-]{1,50}$'");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("generating")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tests_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_tests_created");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_tests_status");

                    b.ToTable("tests", null, t =>
                        {
                            t.HasCheckConstraint("chk_tests_status", "status IN ('generating', 'ready', 'archived')");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("idx_attempts_test_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_attempts_incomplete")
                        .HasFilter("finished_at IS NULL");

                    b.HasIndex("UserId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_attempts_started");

                    b.ToTable("test_attempts", null, t =>
                        {
                            t.HasCheckConstraint("chk_attempts_counts", "(total_questions IS NULL AND correct_answers IS NULL) OR (total_questions >= 0 AND correct_answers >= 0 AND correct_answers <= total_questions)");

                            t.HasCheckConstraint("chk_attempts_score", "score IS NULL OR (score >= 0.0 AND score <= 1.0)");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.TestBlock", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.HasKey("TestId", "BlockId");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("idx_test_blocks_block");

                    b.ToTable("test_blocks", (string)null);
                });

            modelBuilder.Entity("Lexify.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EnglishLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("english_level");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LastActiveAt")
                        .IsDescending()
                        .HasDatabaseName("idx_users_last_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_users_status")
                        .HasFilter("status != 'active'");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_english_level", "english_level IS NULL OR english_level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')");

                            t.HasCheckConstraint("chk_users_role", "role IN ('user', 'moderator', 'admin')");

                            t.HasCheckConstraint("chk_users_status", "status IN ('active', 'suspended', 'deleted')");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<bool>("ConfidenceFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("confidence_flag");

                    b.Property<string>("ConfidenceNote")
                        .HasColumnType("text")
                        .HasColumnName("confidence_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5)
                        .HasColumnName("ease_factor");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text")
                        .HasColumnName("example_sentence");

                    b.Property<int>("IntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("interval_days");

                    b.Property<DateTimeOffset>("NextReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("repetitions");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("term");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.Property<string>("WordType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("word")
                        .HasColumnName("word_type");

                    b.HasKey("Id");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("idx_words_confidence")
                        .HasFilter("confidence_flag = TRUE");

                    b.HasIndex("NextReviewAt")
                        .HasDatabaseName("idx_words_due_review");

                    b.HasIndex("Term")
                        .HasDatabaseName("idx_words_term_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Term"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Term"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Translation")
                        .HasDatabaseName("idx_words_translation_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Translation"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Translation"), new[] { "gin_trgm_ops" });

                    b.HasIndex("BlockId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_words_created");

                    b.HasIndex("BlockId", "SortOrder")
                        .HasDatabaseName("idx_words_sort");

                    b.ToTable("words", null, t =>
                        {
                            t.HasCheckConstraint("chk_words_ease", "ease_factor >= 1.3");

                            t.HasCheckConstraint("chk_words_interval", "interval_days >= 1");

                            t.HasCheckConstraint("chk_words_reps", "repetitions >= 0");

                            t.HasCheckConstraint("chk_words_term", "LENGTH(TRIM(term)) > 0");

                            t.HasCheckConstraint("chk_words_trans", "LENGTH(TRIM(translation)) > 0");

                            t.HasCheckConstraint("chk_words_type", "word_type IN ('word', 'phrase', 'idiom', 'expression')");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.WordBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint")
                        .HasColumnName("language_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_word_blocks_user_id");

                    b.HasIndex("UserId", "LanguageId")
                        .HasDatabaseName("idx_word_blocks_language");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_word_blocks_updated");

                    b.ToTable("word_blocks", null, t =>
                        {
                            t.HasCheckConstraint("chk_word_blocks_count", "word_count >= 0");

                            t.HasCheckConstraint("chk_word_blocks_title", "LENGTH(TRIM(title)) > 0");
                        });
                });

            modelBuilder.Entity("Lexify.Domain.Entities.AiCallLog", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_logs_user");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.TestAttempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_attempt");

                    b.HasOne("Lexify.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_question");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_admin");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.BlockTag", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.WordBlock", null)
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_block_tags_block");

                    b.HasOne("Lexify.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_block_tags_tag");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Question", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_test");

                    b.HasOne("Lexify.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_questions_word");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_question");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_replaced_by");

                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.SystemSetting", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_settings_updated_by");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_user");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Test", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tests_user");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.TestAttempt", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_test");

                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_user");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.TestBlock", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.WordBlock", null)
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_blocks_block");

                    b.HasOne("Lexify.Domain.Entities.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_blocks_test");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Word", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.WordBlock", null)
                        .WithMany("Words")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_words_block");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.WordBlock", b =>
                {
                    b.HasOne("Lexify.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_word_blocks_language");

                    b.HasOne("Lexify.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_blocks_user");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.Test", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.TestAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Lexify.Domain.Entities.WordBlock", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
