export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/',
  BLOCKS: '/blocks',
  BLOCK_DETAIL: (id: string) => `/blocks/${id}`,
  WORD_IMPORT: (blockId: string) => `/blocks/${blockId}/import`,
  TESTS: '/tests',
  TEST_CREATE: '/tests/new',
  TEST_RUNNER: (id: string) => `/tests/${id}/run`,
  TEST_RESULTS: (id: string) => `/tests/${id}/results`,
  REVIEW: '/review',
  PRACTICE_CHAT: '/practice/chat',
  PRACTICE_CHAT_HISTORY: '/practice/chat/history',
  PRACTICE_CHAT_SESSION: (id: string) => `/practice/chat/${id}`,
  STATS: '/stats',
  PROFILE: '/profile',
  SEARCH: '/search',
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    AI_MONITOR: '/admin/ai',
    SETTINGS: '/admin/settings',
    LANGUAGES: '/admin/languages',
    AUDIT: '/admin/audit',
  },
} as const
