export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/',
  BLOCKS: '/blocks',
  BLOCK_DETAIL: (id: string) => `/blocks/${id}`,
  WORD_IMPORT: (blockId: string) => `/blocks/${blockId}/import`,
  TESTS: '/tests',
  TEST_CREATE: '/tests/new',
  TEST_RUNNER: (id: string) => `/tests/${id}/run`,
  TEST_RESULTS: (id: string) => `/tests/${id}/results`,
  REVIEW: '/review',
  PROFILE: '/profile',
  SEARCH: '/search',
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    AI_MONITOR: '/admin/ai',
    SETTINGS: '/admin/settings',
    LANGUAGES: '/admin/languages',
    AUDIT: '/admin/audit',
  },
} as const
