using Lexify.Application.Abstractions;
using Lexify.Infrastructure.Settings;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Lexify.Infrastructure.Services;

/// <summary>
/// Writes attachments to a local directory (a mounted volume in Docker), mirroring how
/// <see cref="PiperTtsService"/> caches synthesized audio. The storage name is a fresh Guid plus the
/// extension the content sniffer decided on — never anything the user supplied.
/// </summary>
public sealed partial class LocalFeedbackAttachmentStorage : IFeedbackAttachmentStorage
{
    private readonly string _directory;
    private readonly ILogger<LocalFeedbackAttachmentStorage> _logger;

    public LocalFeedbackAttachmentStorage(
        IOptions<FeedbackStorageSettings> options, ILogger<LocalFeedbackAttachmentStorage> logger)
    {
        _directory = Path.GetFullPath(options.Value.Directory);
        _logger = logger;
    }

    public async Task<string> SaveAsync(byte[] content, string extension, CancellationToken ct = default)
    {
        Directory.CreateDirectory(_directory);

        var storageName = $"{Guid.NewGuid():N}{extension}";
        await File.WriteAllBytesAsync(Path.Combine(_directory, storageName), content, ct);
        return storageName;
    }

    public async Task<byte[]?> ReadAsync(string storageName, CancellationToken ct = default)
    {
        var path = ResolvePath(storageName);
        if (path is null || !File.Exists(path))
            return null;

        return await File.ReadAllBytesAsync(path, ct);
    }

    public Task DeleteAsync(string storageName, CancellationToken ct = default)
    {
        var path = ResolvePath(storageName);
        if (path is null)
            return Task.CompletedTask;

        try
        {
            File.Delete(path);
        }
        catch (IOException ex)
        {
            // Orphaned bytes are harmless; failing the surrounding request over them is not.
            LogDeleteFailure(_logger, storageName, ex);
        }

        return Task.CompletedTask;
    }

    [LoggerMessage(Level = LogLevel.Warning, Message = "Could not delete feedback attachment {StorageName}.")]
    static partial void LogDeleteFailure(ILogger logger, string storageName, Exception ex);

    /// <summary>
    /// Defence in depth: storage names are generated by <see cref="SaveAsync"/>, but this class is the
    /// only thing standing between a DB value and the filesystem, so re-check that the resolved path
    /// really sits inside the storage directory.
    /// </summary>
    private string? ResolvePath(string storageName)
    {
        if (string.IsNullOrWhiteSpace(storageName) || storageName != Path.GetFileName(storageName))
            return null;

        var fullPath = Path.GetFullPath(Path.Combine(_directory, storageName));
        return fullPath.StartsWith(_directory + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            ? fullPath
            : null;
    }
}
